const express = require('express');
const path = require('path');
const fs = require('fs');

const PORT = process.env.PORT || 3000;
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');

// --- Word lists ---
// Two separate lists, both generated by scripts/build-dictionary.js:
//   dictionary.js    answers  — common words, so puzzles are fair
//   valid-words.txt  guesses  — a full dictionary, so real words are accepted
// The Docker image flattens both files next to server.js; a checkout keeps
// dictionary.js at the repo root.
function resolveList(name) {
  const candidates = [path.join(__dirname, name), path.join(__dirname, '..', name)];
  const found = candidates.find((file) => fs.existsSync(file));
  if (!found) throw new Error(`Missing word list ${name} (looked in ${candidates.join(', ')})`);
  return found;
}

const ANSWERS_BY_LENGTH = loadAnswers(resolveList('dictionary.js'));
const VALID_BY_LENGTH = loadValidWords(resolveList('valid-words.txt'));

function loadAnswers(file) {
  const code = fs.readFileSync(file, 'utf8');
  const buckets = {};
  // Generated file, one `  <length>: [ ... ]` entry per line.
  for (const [, len, words] of code.matchAll(/^\s*(\d+):\s*(\[.*?\]),?\s*$/gm)) {
    buckets[len] = JSON.parse(words);
  }
  if (!Object.keys(buckets).length) throw new Error(`Could not parse ${file}`);
  return buckets;
}

function loadValidWords(file) {
  const sets = {};
  for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
    const word = line.trim();
    if (!word) continue;
    (sets[word.length] ||= new Set()).add(word);
  }
  if (!Object.keys(sets).length) throw new Error(`Could not parse ${file}`);
  return sets;
}

// Every answer must also be a legal guess, or a player could be shown a word
// the validator would reject.
for (const [len, words] of Object.entries(ANSWERS_BY_LENGTH)) {
  const valid = VALID_BY_LENGTH[len] || new Set();
  const missing = words.filter((w) => !valid.has(w));
  if (missing.length) {
    throw new Error(`Answers missing from valid-words.txt: ${missing.slice(0, 5).join(', ')}`);
  }
}

// --- Persistence helpers (plain files on a mounted volume) ---
fs.mkdirSync(DATA_DIR, { recursive: true });

const BANNED_FILE = path.join(DATA_DIR, 'banned.json');
const FEEDBACK_FILE = path.join(DATA_DIR, 'feedback.jsonl');

function readJSON(file, fallback) {
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; }
}

// Kept in memory: /word consults it on every request, and re-reading the file
// each time put a synchronous disk read in the hot path.
const banned = new Set(readJSON(BANNED_FILE, []));

function writeAtomic(file, contents) {
  const tmp = `${file}.tmp`;
  fs.writeFileSync(tmp, contents);
  fs.renameSync(tmp, file);
}

function banWord(word) {
  if (banned.has(word)) return;
  banned.add(word);
  writeAtomic(BANNED_FILE, JSON.stringify([...banned]));
}

function recordFeedback(word, rating) {
  // Append-only: rewriting one growing JSON array per request is O(n) and
  // loses entries when two requests interleave.
  fs.appendFileSync(FEEDBACK_FILE, JSON.stringify({ word, rating, at: new Date().toISOString() }) + '\n');
}

// --- Express app ---
const app = express();
app.use(express.json({ limit: '4kb' }));

// GET /word?length=5
app.get('/word', (req, res) => {
  const length = parseInt(req.query.length, 10);
  if (!length || length < 5 || length > 10) {
    return res.status(400).json({ error: 'length must be between 5 and 10' });
  }

  const pool = ANSWERS_BY_LENGTH[length] || [];
  if (!pool.length) return res.status(404).json({ error: 'No words for this length' });

  const available = banned.size ? pool.filter((w) => !banned.has(w)) : pool;
  if (!available.length) return res.status(404).json({ error: 'No available words (all banned)' });

  const word = available[Math.floor(Math.random() * available.length)];
  res.json({ word });
});

// POST /validate  { word: string }
app.post('/validate', (req, res) => {
  const word = String(req.body?.word || '').trim().toLowerCase();
  if (!/^[a-z]{5,10}$/.test(word)) {
    return res.status(400).json({ error: 'Invalid word format' });
  }
  const valid = (VALID_BY_LENGTH[word.length] || new Set()).has(word);
  res.json({ valid });
});

// POST /feedback  { word: string, rating: 'up' | 'down' | 'skip' }
app.post('/feedback', (req, res) => {
  const word = String(req.body?.word || '').trim().toLowerCase();
  const rating = String(req.body?.rating || '').trim();

  if (!word || !['up', 'down', 'skip'].includes(rating)) {
    return res.status(400).json({ error: 'Invalid input' });
  }
  // Only words we actually hand out can be rated, so a stray or crafted
  // request cannot push arbitrary strings into the ban list.
  if (!(ANSWERS_BY_LENGTH[word.length] || []).includes(word)) {
    return res.status(400).json({ error: 'Unknown word' });
  }

  recordFeedback(word, rating);
  if (rating === 'down') banWord(word);

  res.json({ ok: true });
});

app.get('/health', (req, res) => res.json({ ok: true, banned: banned.size }));

// Malformed JSON bodies should be a clean 400, not an HTML stack trace.
app.use((err, req, res, next) => {
  if (err) return res.status(400).json({ error: 'Bad request' });
  next();
});

app.listen(PORT, () => console.log(`word-runner API listening on :${PORT}`));
